# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: opal-async 1.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "opal-async".freeze
  s.version = "1.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Ravenstine".freeze, "Andy Maleh".freeze]
  s.date = "2020-10-11"
  s.description = "Provides non-blocking tasks and enumerators for Opal.".freeze
  s.email = ["benjamin@pixelstreetinc.com".freeze, "andy.am@gmail.com".freeze]
  s.extra_rdoc_files = [
    "CHANGELOG.md",
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "LICENSE.txt",
    "README.md",
    "VERSION",
    "lib/opal-async.rb",
    "lib/opal/async.rb",
    "opal/async.rb",
    "opal/async/countdown.rb",
    "opal/async/enumerator.rb",
    "opal/async/ext/thread.rb",
    "opal/async/interval.rb",
    "opal/async/task.rb",
    "opal/async/timeout.rb",
    "opal/opal-async.rb"
  ]
  s.homepage = "http://github.com/AndyObtiva/opal-async".freeze
  s.licenses = ["MIT".freeze]
  s.rdoc_options = ["--main".freeze, "README".freeze, "--line-numbers".freeze, "--include".freeze, "opal".freeze]
  s.rubygems_version = "3.1.4".freeze
  s.summary = "Provides non-blocking tasks and enumerators for Opal.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<opal>.freeze, [">= 1.0.0", "< 2.0.0"])
    s.add_development_dependency(%q<opal-rspec>.freeze, [">= 0"])
    s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_development_dependency(%q<bundler>.freeze, [">= 1.0"])
    s.add_development_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
    s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
  else
    s.add_dependency(%q<opal>.freeze, [">= 1.0.0", "< 2.0.0"])
    s.add_dependency(%q<opal-rspec>.freeze, [">= 0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<bundler>.freeze, [">= 1.0"])
    s.add_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
  end
end

